---

- name: Manage limits
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.name }}" 
    value: "{{ item.value }}" 
  with_items:
    "{{ manage_limits_values }}"
