---
# tasks file for users

- name: Manage users
  user:
    append: "{{ item['append'] | default(omit) }}"
    comment: "{{ item['comment'] | default(omit) }}"
    createhome: "{{ item['createhome'] | default(omit) }}"
    expires: "{{ item['expires'] | default(omit) }}"
    force: "{{ item['force'] | default(omit) }}"
    generate_ssh_key: "{{ item['generate_ssh_key'] | default(omit) }}"
    group: "{{ item['group'] | default(omit) }}"
    groups: "{{ item['groups'] | default(omit) }}"
    home: "{{ item['home'] | default(omit) }}"
    login_class: "{{ item['login_class'] | default(omit) }}"
    move_home: "{{ item['move_home'] | default(omit) }}"
    name: "{{ item['name'] | default(omit) }}"
    non_unique: "{{ item['non_unique'] | default(omit) }}"
    password: "{{ item['password'] | default(omit) }}"
    remove: "{{ item['remove'] | default(omit) }}"
    seuser: "{{ item['seuser'] | default(omit) }}"
    shell: "{{ item['shell'] | default(omit) }}"
    skeleton: "{{ item['skeleton'] | default(omit) }}"
    ssh_key_bits: "{{ item['ssh_key_bits'] | default(omit) }}"
    ssh_key_comment: "{{ item['ssh_key_comment'] | default(omit) }}"
    ssh_key_file: "{{ item['ssh_key_file'] | default(omit) }}"
    ssh_key_passphrase: "{{ item['ssh_key_passphrase'] | default(omit) }}"
    ssh_key_type: "{{ item['ssh_key_type'] | default(omit) }}"
    state: "{{ item['state'] | default(omit) }}"
    system: "{{ item['system'] | default(omit) }}"
    uid: "{{ item['uid'] | default(omit) }}"
    update_password: "{{ item['update_password'] | default(omit) }}"
  with_items:
    - "{{ users_list }}"
  when: users_list|length > 0
